name: Build

on:
  push:
    branches: [main]
  schedule:
    # Run every 6 hours at 43 minutes past the hour.
    - cron: "43 */6 * * *"
  workflow_dispatch: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Validate shell scripts
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: 'yes'
          scandir: .

  build:
    name: Build and Publish Blocklist
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: latest

      - name: Compile blocklist
        run: ./build.sh

      - name: Upload blocklist to GitHub as a site
        uses: actions/upload-pages-artifact@v4
        with:
          path: out/

      - name: Deploy site to GitHub Pages
        uses: actions/deploy-pages@v4
